export enum AppStorageMap {
  HUAWEI_ACCOUNT = 'huaweiAccount',
  USER_INFO = 'userInfo',
  DECORATION_INFO='decorationInfo',
  CURRENT_CITY='currentCity'
}

export enum RouterMap {
  //   隐私政策
  TERMS_OF_SERVICE_PAGE='TermsOfServicePage',
  //   用户协议
  PRIVACY_POLICY_PAGE='PrivacyPolicyPage',
  //   一键登录
  QUICK_LOGIN_PAGE='QuickLoginPage',
  //  设置
  SETTINGS_PAGE = 'SettingsPage',
  //  个人信息
  PERSON_INFO_PAGE = 'PersonalInfo',
  //  我的收藏
  MY_COLLECTION='MyCollection',
  //  我的装修信息
  MY_DECORATION_INFO='MyDecorationInfo',
  //  设计师主页
  DESIGNER_PAGE='DesignerPage',
  //  案例详情
  CASE_DETAIL_PAGE='CaseDetailPage',
  //  所有城市
  ALL_CITY_PAGE='AllCityPage',
  //  搜索页
  SEARCH_PAGE='SearchPage',
  //  家装案例
  HOME_CASE_PAGE='HomeCasePage',
  //  装修报价
  PRICE_PAGE='PricePage',
  //  报价清单
  LIST_PAGE='ListPage',
  //  定制结果
  CUSTOM_RESULT='CustomResult',
  //  设计师对应案例列表
  OWN_CASE_PAGE='OwnCasePage',
  //  首页
  HOME = 'HomePage',
  //  定制设计
  CUSTOM = 'CustomPage',
  //  找设计师
  FIND='FindPage'
}